// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Attention_layer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v17_0_address0,
        v17_0_ce0,
        v17_0_q0,
        v17_1_address0,
        v17_1_ce0,
        v17_1_q0,
        v17_2_address0,
        v17_2_ce0,
        v17_2_q0,
        v17_3_address0,
        v17_3_ce0,
        v17_3_q0,
        v18_0_address0,
        v18_0_ce0,
        v18_0_q0,
        v18_1_address0,
        v18_1_ce0,
        v18_1_q0,
        v18_2_address0,
        v18_2_ce0,
        v18_2_q0,
        v18_3_address0,
        v18_3_ce0,
        v18_3_q0,
        v19_0_0_address0,
        v19_0_0_ce0,
        v19_0_0_we0,
        v19_0_0_d0,
        v19_0_0_q0,
        v19_0_1_address0,
        v19_0_1_ce0,
        v19_0_1_we0,
        v19_0_1_d0,
        v19_0_1_q0,
        v19_0_2_address0,
        v19_0_2_ce0,
        v19_0_2_we0,
        v19_0_2_d0,
        v19_0_2_q0,
        v19_0_3_address0,
        v19_0_3_ce0,
        v19_0_3_we0,
        v19_0_3_d0,
        v19_0_3_q0,
        v19_1_0_address0,
        v19_1_0_ce0,
        v19_1_0_we0,
        v19_1_0_d0,
        v19_1_0_q0,
        v19_1_1_address0,
        v19_1_1_ce0,
        v19_1_1_we0,
        v19_1_1_d0,
        v19_1_1_q0,
        v19_1_2_address0,
        v19_1_2_ce0,
        v19_1_2_we0,
        v19_1_2_d0,
        v19_1_2_q0,
        v19_1_3_address0,
        v19_1_3_ce0,
        v19_1_3_we0,
        v19_1_3_d0,
        v19_1_3_q0,
        v19_2_0_address0,
        v19_2_0_ce0,
        v19_2_0_we0,
        v19_2_0_d0,
        v19_2_0_q0,
        v19_2_1_address0,
        v19_2_1_ce0,
        v19_2_1_we0,
        v19_2_1_d0,
        v19_2_1_q0,
        v19_2_2_address0,
        v19_2_2_ce0,
        v19_2_2_we0,
        v19_2_2_d0,
        v19_2_2_q0,
        v19_2_3_address0,
        v19_2_3_ce0,
        v19_2_3_we0,
        v19_2_3_d0,
        v19_2_3_q0,
        v19_3_0_address0,
        v19_3_0_ce0,
        v19_3_0_we0,
        v19_3_0_d0,
        v19_3_0_q0,
        v19_3_1_address0,
        v19_3_1_ce0,
        v19_3_1_we0,
        v19_3_1_d0,
        v19_3_1_q0,
        v19_3_2_address0,
        v19_3_2_ce0,
        v19_3_2_we0,
        v19_3_2_d0,
        v19_3_2_q0,
        v19_3_3_address0,
        v19_3_3_ce0,
        v19_3_3_we0,
        v19_3_3_d0,
        v19_3_3_q0
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] v17_0_address0;
output   v17_0_ce0;
input  [31:0] v17_0_q0;
output  [7:0] v17_1_address0;
output   v17_1_ce0;
input  [31:0] v17_1_q0;
output  [7:0] v17_2_address0;
output   v17_2_ce0;
input  [31:0] v17_2_q0;
output  [7:0] v17_3_address0;
output   v17_3_ce0;
input  [31:0] v17_3_q0;
output  [7:0] v18_0_address0;
output   v18_0_ce0;
input  [31:0] v18_0_q0;
output  [7:0] v18_1_address0;
output   v18_1_ce0;
input  [31:0] v18_1_q0;
output  [7:0] v18_2_address0;
output   v18_2_ce0;
input  [31:0] v18_2_q0;
output  [7:0] v18_3_address0;
output   v18_3_ce0;
input  [31:0] v18_3_q0;
output  [3:0] v19_0_0_address0;
output   v19_0_0_ce0;
output   v19_0_0_we0;
output  [31:0] v19_0_0_d0;
input  [31:0] v19_0_0_q0;
output  [3:0] v19_0_1_address0;
output   v19_0_1_ce0;
output   v19_0_1_we0;
output  [31:0] v19_0_1_d0;
input  [31:0] v19_0_1_q0;
output  [3:0] v19_0_2_address0;
output   v19_0_2_ce0;
output   v19_0_2_we0;
output  [31:0] v19_0_2_d0;
input  [31:0] v19_0_2_q0;
output  [3:0] v19_0_3_address0;
output   v19_0_3_ce0;
output   v19_0_3_we0;
output  [31:0] v19_0_3_d0;
input  [31:0] v19_0_3_q0;
output  [3:0] v19_1_0_address0;
output   v19_1_0_ce0;
output   v19_1_0_we0;
output  [31:0] v19_1_0_d0;
input  [31:0] v19_1_0_q0;
output  [3:0] v19_1_1_address0;
output   v19_1_1_ce0;
output   v19_1_1_we0;
output  [31:0] v19_1_1_d0;
input  [31:0] v19_1_1_q0;
output  [3:0] v19_1_2_address0;
output   v19_1_2_ce0;
output   v19_1_2_we0;
output  [31:0] v19_1_2_d0;
input  [31:0] v19_1_2_q0;
output  [3:0] v19_1_3_address0;
output   v19_1_3_ce0;
output   v19_1_3_we0;
output  [31:0] v19_1_3_d0;
input  [31:0] v19_1_3_q0;
output  [3:0] v19_2_0_address0;
output   v19_2_0_ce0;
output   v19_2_0_we0;
output  [31:0] v19_2_0_d0;
input  [31:0] v19_2_0_q0;
output  [3:0] v19_2_1_address0;
output   v19_2_1_ce0;
output   v19_2_1_we0;
output  [31:0] v19_2_1_d0;
input  [31:0] v19_2_1_q0;
output  [3:0] v19_2_2_address0;
output   v19_2_2_ce0;
output   v19_2_2_we0;
output  [31:0] v19_2_2_d0;
input  [31:0] v19_2_2_q0;
output  [3:0] v19_2_3_address0;
output   v19_2_3_ce0;
output   v19_2_3_we0;
output  [31:0] v19_2_3_d0;
input  [31:0] v19_2_3_q0;
output  [3:0] v19_3_0_address0;
output   v19_3_0_ce0;
output   v19_3_0_we0;
output  [31:0] v19_3_0_d0;
input  [31:0] v19_3_0_q0;
output  [3:0] v19_3_1_address0;
output   v19_3_1_ce0;
output   v19_3_1_we0;
output  [31:0] v19_3_1_d0;
input  [31:0] v19_3_1_q0;
output  [3:0] v19_3_2_address0;
output   v19_3_2_ce0;
output   v19_3_2_we0;
output  [31:0] v19_3_2_d0;
input  [31:0] v19_3_2_q0;
output  [3:0] v19_3_3_address0;
output   v19_3_3_ce0;
output   v19_3_3_we0;
output  [31:0] v19_3_3_d0;
input  [31:0] v19_3_3_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] v19_0_0_address0;
reg v19_0_0_ce0;
reg v19_0_0_we0;
reg[31:0] v19_0_0_d0;
reg[3:0] v19_0_1_address0;
reg v19_0_1_ce0;
reg v19_0_1_we0;
reg[31:0] v19_0_1_d0;
reg[3:0] v19_0_2_address0;
reg v19_0_2_ce0;
reg v19_0_2_we0;
reg[31:0] v19_0_2_d0;
reg[3:0] v19_0_3_address0;
reg v19_0_3_ce0;
reg v19_0_3_we0;
reg[31:0] v19_0_3_d0;
reg[3:0] v19_1_0_address0;
reg v19_1_0_ce0;
reg v19_1_0_we0;
reg[31:0] v19_1_0_d0;
reg[3:0] v19_1_1_address0;
reg v19_1_1_ce0;
reg v19_1_1_we0;
reg[31:0] v19_1_1_d0;
reg[3:0] v19_1_2_address0;
reg v19_1_2_ce0;
reg v19_1_2_we0;
reg[31:0] v19_1_2_d0;
reg[3:0] v19_1_3_address0;
reg v19_1_3_ce0;
reg v19_1_3_we0;
reg[31:0] v19_1_3_d0;
reg[3:0] v19_2_0_address0;
reg v19_2_0_ce0;
reg v19_2_0_we0;
reg[31:0] v19_2_0_d0;
reg[3:0] v19_2_1_address0;
reg v19_2_1_ce0;
reg v19_2_1_we0;
reg[31:0] v19_2_1_d0;
reg[3:0] v19_2_2_address0;
reg v19_2_2_ce0;
reg v19_2_2_we0;
reg[31:0] v19_2_2_d0;
reg[3:0] v19_2_3_address0;
reg v19_2_3_ce0;
reg v19_2_3_we0;
reg[31:0] v19_2_3_d0;
reg[3:0] v19_3_0_address0;
reg v19_3_0_ce0;
reg v19_3_0_we0;
reg[31:0] v19_3_0_d0;
reg[3:0] v19_3_1_address0;
reg v19_3_1_ce0;
reg v19_3_1_we0;
reg[31:0] v19_3_1_d0;
reg[3:0] v19_3_2_address0;
reg v19_3_2_ce0;
reg v19_3_2_we0;
reg[31:0] v19_3_2_d0;
reg[3:0] v19_3_3_address0;
reg v19_3_3_ce0;
reg v19_3_3_we0;
reg[31:0] v19_3_3_d0;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] v20_fu_594_p2;
reg   [3:0] v20_reg_868;
wire    ap_CS_fsm_state2;
wire   [1:0] trunc_ln42_fu_600_p1;
reg   [1:0] trunc_ln42_reg_873;
wire   [0:0] icmp_ln40_fu_588_p2;
wire   [4:0] sub_ln42_fu_630_p2;
reg   [4:0] sub_ln42_reg_877;
wire   [3:0] v21_fu_642_p2;
wire    ap_CS_fsm_state3;
wire   [7:0] add_ln48_fu_697_p2;
reg   [7:0] add_ln48_reg_896;
wire    ap_CS_fsm_state5;
wire   [3:0] select_ln51_fu_715_p3;
reg   [3:0] select_ln51_reg_901;
wire   [0:0] icmp_ln48_fu_691_p2;
wire   [3:0] select_ln51_1_fu_723_p3;
reg   [3:0] select_ln51_1_reg_906;
wire   [1:0] trunc_ln51_fu_731_p1;
reg   [1:0] trunc_ln51_reg_911;
wire   [1:0] trunc_ln51_1_fu_767_p1;
reg   [1:0] trunc_ln51_1_reg_916;
reg   [3:0] v19_0_0_addr_1_reg_921;
reg   [3:0] v19_0_1_addr_1_reg_926;
reg   [3:0] v19_0_2_addr_1_reg_931;
reg   [3:0] v19_0_3_addr_1_reg_936;
reg   [3:0] v19_1_0_addr_1_reg_941;
reg   [3:0] v19_1_1_addr_1_reg_946;
reg   [3:0] v19_1_2_addr_1_reg_951;
reg   [3:0] v19_1_3_addr_1_reg_956;
reg   [3:0] v19_2_0_addr_1_reg_961;
reg   [3:0] v19_2_1_addr_1_reg_966;
reg   [3:0] v19_2_2_addr_1_reg_971;
reg   [3:0] v19_2_3_addr_1_reg_976;
reg   [3:0] v19_3_0_addr_1_reg_981;
reg   [3:0] v19_3_1_addr_1_reg_986;
reg   [3:0] v19_3_2_addr_1_reg_991;
reg   [3:0] v19_3_3_addr_1_reg_996;
wire   [31:0] v36_fu_821_p18;
wire    ap_CS_fsm_state6;
wire   [3:0] j1_fu_860_p2;
wire    ap_CS_fsm_state9;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_A_0_address0;
wire    grp_gemm_systolic_array_5_fu_515_A_0_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_A_0_d0;
wire    grp_gemm_systolic_array_5_fu_515_A_0_we0;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_A_0_address1;
wire    grp_gemm_systolic_array_5_fu_515_A_0_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_A_0_d1;
wire    grp_gemm_systolic_array_5_fu_515_A_0_we1;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_A_1_address0;
wire    grp_gemm_systolic_array_5_fu_515_A_1_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_A_1_d0;
wire    grp_gemm_systolic_array_5_fu_515_A_1_we0;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_A_1_address1;
wire    grp_gemm_systolic_array_5_fu_515_A_1_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_A_1_d1;
wire    grp_gemm_systolic_array_5_fu_515_A_1_we1;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_A_2_address0;
wire    grp_gemm_systolic_array_5_fu_515_A_2_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_A_2_d0;
wire    grp_gemm_systolic_array_5_fu_515_A_2_we0;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_A_2_address1;
wire    grp_gemm_systolic_array_5_fu_515_A_2_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_A_2_d1;
wire    grp_gemm_systolic_array_5_fu_515_A_2_we1;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_A_3_address0;
wire    grp_gemm_systolic_array_5_fu_515_A_3_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_A_3_d0;
wire    grp_gemm_systolic_array_5_fu_515_A_3_we0;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_A_3_address1;
wire    grp_gemm_systolic_array_5_fu_515_A_3_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_A_3_d1;
wire    grp_gemm_systolic_array_5_fu_515_A_3_we1;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_B_0_address0;
wire    grp_gemm_systolic_array_5_fu_515_B_0_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_B_0_d0;
wire    grp_gemm_systolic_array_5_fu_515_B_0_we0;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_B_0_address1;
wire    grp_gemm_systolic_array_5_fu_515_B_0_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_B_0_d1;
wire    grp_gemm_systolic_array_5_fu_515_B_0_we1;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_B_1_address0;
wire    grp_gemm_systolic_array_5_fu_515_B_1_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_B_1_d0;
wire    grp_gemm_systolic_array_5_fu_515_B_1_we0;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_B_1_address1;
wire    grp_gemm_systolic_array_5_fu_515_B_1_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_B_1_d1;
wire    grp_gemm_systolic_array_5_fu_515_B_1_we1;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_B_2_address0;
wire    grp_gemm_systolic_array_5_fu_515_B_2_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_B_2_d0;
wire    grp_gemm_systolic_array_5_fu_515_B_2_we0;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_B_2_address1;
wire    grp_gemm_systolic_array_5_fu_515_B_2_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_B_2_d1;
wire    grp_gemm_systolic_array_5_fu_515_B_2_we1;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_B_3_address0;
wire    grp_gemm_systolic_array_5_fu_515_B_3_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_B_3_d0;
wire    grp_gemm_systolic_array_5_fu_515_B_3_we0;
wire   [7:0] grp_gemm_systolic_array_5_fu_515_B_3_address1;
wire    grp_gemm_systolic_array_5_fu_515_B_3_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_B_3_d1;
wire    grp_gemm_systolic_array_5_fu_515_B_3_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_0_0_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_0_0_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_0_0_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_0_0_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_0_0_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_0_0_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_0_0_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_0_0_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_0_1_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_0_1_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_0_1_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_0_1_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_0_1_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_0_1_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_0_1_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_0_1_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_0_2_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_0_2_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_0_2_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_0_2_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_0_2_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_0_2_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_0_2_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_0_2_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_0_3_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_0_3_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_0_3_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_0_3_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_0_3_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_0_3_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_0_3_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_0_3_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_1_0_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_1_0_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_1_0_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_1_0_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_1_0_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_1_0_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_1_0_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_1_0_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_1_1_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_1_1_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_1_1_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_1_1_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_1_1_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_1_1_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_1_1_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_1_1_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_1_2_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_1_2_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_1_2_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_1_2_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_1_2_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_1_2_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_1_2_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_1_2_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_1_3_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_1_3_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_1_3_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_1_3_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_1_3_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_1_3_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_1_3_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_1_3_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_2_0_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_2_0_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_2_0_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_2_0_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_2_0_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_2_0_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_2_0_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_2_0_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_2_1_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_2_1_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_2_1_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_2_1_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_2_1_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_2_1_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_2_1_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_2_1_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_2_2_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_2_2_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_2_2_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_2_2_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_2_2_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_2_2_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_2_2_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_2_2_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_2_3_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_2_3_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_2_3_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_2_3_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_2_3_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_2_3_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_2_3_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_2_3_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_3_0_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_3_0_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_3_0_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_3_0_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_3_0_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_3_0_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_3_0_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_3_0_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_3_1_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_3_1_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_3_1_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_3_1_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_3_1_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_3_1_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_3_1_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_3_1_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_3_2_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_3_2_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_3_2_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_3_2_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_3_2_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_3_2_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_3_2_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_3_2_we1;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_3_3_address0;
wire    grp_gemm_systolic_array_5_fu_515_C_3_3_ce0;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_3_3_d0;
wire    grp_gemm_systolic_array_5_fu_515_C_3_3_we0;
wire   [3:0] grp_gemm_systolic_array_5_fu_515_C_3_3_address1;
wire    grp_gemm_systolic_array_5_fu_515_C_3_3_ce1;
wire   [31:0] grp_gemm_systolic_array_5_fu_515_C_3_3_d1;
wire    grp_gemm_systolic_array_5_fu_515_C_3_3_we1;
wire    grp_gemm_systolic_array_5_fu_515_ap_start;
wire    grp_gemm_systolic_array_5_fu_515_ap_done;
wire    grp_gemm_systolic_array_5_fu_515_ap_ready;
wire    grp_gemm_systolic_array_5_fu_515_ap_idle;
reg    grp_gemm_systolic_array_5_fu_515_ap_continue;
reg   [3:0] v20_0_reg_460;
wire   [0:0] icmp_ln41_fu_636_p2;
reg   [3:0] v21_0_reg_471;
reg   [7:0] indvar_flatten_reg_482;
wire    ap_CS_fsm_state4;
wire    ap_sync_grp_gemm_systolic_array_5_fu_515_ap_ready;
wire    ap_sync_grp_gemm_systolic_array_5_fu_515_ap_done;
reg    ap_block_state4_on_subcall_done;
reg   [3:0] i2_0_reg_493;
reg   [3:0] j1_0_reg_504;
reg    grp_gemm_systolic_array_5_fu_515_ap_start_reg;
reg    ap_sync_reg_grp_gemm_systolic_array_5_fu_515_ap_ready;
reg    ap_sync_reg_grp_gemm_systolic_array_5_fu_515_ap_done;
wire  signed [63:0] sext_ln42_fu_671_p1;
wire  signed [63:0] sext_ln51_fu_791_p1;
wire   [1:0] trunc_ln42_1_fu_648_p1;
wire   [31:0] grp_fu_567_p2;
wire   [1:0] lshr_ln_fu_604_p4;
wire   [3:0] tmp_fu_618_p3;
wire   [4:0] zext_ln42_1_fu_626_p1;
wire   [4:0] zext_ln42_fu_614_p1;
wire   [1:0] tmp_508_fu_652_p4;
wire   [4:0] zext_ln42_2_fu_662_p1;
wire   [4:0] add_ln42_fu_666_p2;
wire   [0:0] icmp_ln49_fu_709_p2;
wire   [3:0] i2_fu_703_p2;
wire   [1:0] zext_ln51_mid2_v_fu_735_p4;
wire   [3:0] tmp_233_fu_749_p3;
wire   [4:0] zext_ln51_1_fu_757_p1;
wire   [4:0] zext_ln51_fu_745_p1;
wire   [1:0] tmp_507_fu_771_p4;
wire   [4:0] zext_ln51_2_fu_781_p1;
wire   [4:0] sub_ln51_fu_761_p2;
wire   [4:0] add_ln51_fu_785_p2;
wire   [3:0] tmp_231_fu_811_p3;
wire   [4:0] v36_fu_821_p17;
wire    ap_CS_fsm_state10;
reg   [9:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_gemm_systolic_array_5_fu_515_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_gemm_systolic_array_5_fu_515_ap_ready = 1'b0;
#0 ap_sync_reg_grp_gemm_systolic_array_5_fu_515_ap_done = 1'b0;
end

gemm_systolic_array_5 grp_gemm_systolic_array_5_fu_515(
    .A_0_address0(grp_gemm_systolic_array_5_fu_515_A_0_address0),
    .A_0_ce0(grp_gemm_systolic_array_5_fu_515_A_0_ce0),
    .A_0_d0(grp_gemm_systolic_array_5_fu_515_A_0_d0),
    .A_0_q0(v17_0_q0),
    .A_0_we0(grp_gemm_systolic_array_5_fu_515_A_0_we0),
    .A_0_address1(grp_gemm_systolic_array_5_fu_515_A_0_address1),
    .A_0_ce1(grp_gemm_systolic_array_5_fu_515_A_0_ce1),
    .A_0_d1(grp_gemm_systolic_array_5_fu_515_A_0_d1),
    .A_0_q1(32'd0),
    .A_0_we1(grp_gemm_systolic_array_5_fu_515_A_0_we1),
    .A_1_address0(grp_gemm_systolic_array_5_fu_515_A_1_address0),
    .A_1_ce0(grp_gemm_systolic_array_5_fu_515_A_1_ce0),
    .A_1_d0(grp_gemm_systolic_array_5_fu_515_A_1_d0),
    .A_1_q0(v17_1_q0),
    .A_1_we0(grp_gemm_systolic_array_5_fu_515_A_1_we0),
    .A_1_address1(grp_gemm_systolic_array_5_fu_515_A_1_address1),
    .A_1_ce1(grp_gemm_systolic_array_5_fu_515_A_1_ce1),
    .A_1_d1(grp_gemm_systolic_array_5_fu_515_A_1_d1),
    .A_1_q1(32'd0),
    .A_1_we1(grp_gemm_systolic_array_5_fu_515_A_1_we1),
    .A_2_address0(grp_gemm_systolic_array_5_fu_515_A_2_address0),
    .A_2_ce0(grp_gemm_systolic_array_5_fu_515_A_2_ce0),
    .A_2_d0(grp_gemm_systolic_array_5_fu_515_A_2_d0),
    .A_2_q0(v17_2_q0),
    .A_2_we0(grp_gemm_systolic_array_5_fu_515_A_2_we0),
    .A_2_address1(grp_gemm_systolic_array_5_fu_515_A_2_address1),
    .A_2_ce1(grp_gemm_systolic_array_5_fu_515_A_2_ce1),
    .A_2_d1(grp_gemm_systolic_array_5_fu_515_A_2_d1),
    .A_2_q1(32'd0),
    .A_2_we1(grp_gemm_systolic_array_5_fu_515_A_2_we1),
    .A_3_address0(grp_gemm_systolic_array_5_fu_515_A_3_address0),
    .A_3_ce0(grp_gemm_systolic_array_5_fu_515_A_3_ce0),
    .A_3_d0(grp_gemm_systolic_array_5_fu_515_A_3_d0),
    .A_3_q0(v17_3_q0),
    .A_3_we0(grp_gemm_systolic_array_5_fu_515_A_3_we0),
    .A_3_address1(grp_gemm_systolic_array_5_fu_515_A_3_address1),
    .A_3_ce1(grp_gemm_systolic_array_5_fu_515_A_3_ce1),
    .A_3_d1(grp_gemm_systolic_array_5_fu_515_A_3_d1),
    .A_3_q1(32'd0),
    .A_3_we1(grp_gemm_systolic_array_5_fu_515_A_3_we1),
    .B_0_address0(grp_gemm_systolic_array_5_fu_515_B_0_address0),
    .B_0_ce0(grp_gemm_systolic_array_5_fu_515_B_0_ce0),
    .B_0_d0(grp_gemm_systolic_array_5_fu_515_B_0_d0),
    .B_0_q0(v18_0_q0),
    .B_0_we0(grp_gemm_systolic_array_5_fu_515_B_0_we0),
    .B_0_address1(grp_gemm_systolic_array_5_fu_515_B_0_address1),
    .B_0_ce1(grp_gemm_systolic_array_5_fu_515_B_0_ce1),
    .B_0_d1(grp_gemm_systolic_array_5_fu_515_B_0_d1),
    .B_0_q1(32'd0),
    .B_0_we1(grp_gemm_systolic_array_5_fu_515_B_0_we1),
    .B_1_address0(grp_gemm_systolic_array_5_fu_515_B_1_address0),
    .B_1_ce0(grp_gemm_systolic_array_5_fu_515_B_1_ce0),
    .B_1_d0(grp_gemm_systolic_array_5_fu_515_B_1_d0),
    .B_1_q0(v18_1_q0),
    .B_1_we0(grp_gemm_systolic_array_5_fu_515_B_1_we0),
    .B_1_address1(grp_gemm_systolic_array_5_fu_515_B_1_address1),
    .B_1_ce1(grp_gemm_systolic_array_5_fu_515_B_1_ce1),
    .B_1_d1(grp_gemm_systolic_array_5_fu_515_B_1_d1),
    .B_1_q1(32'd0),
    .B_1_we1(grp_gemm_systolic_array_5_fu_515_B_1_we1),
    .B_2_address0(grp_gemm_systolic_array_5_fu_515_B_2_address0),
    .B_2_ce0(grp_gemm_systolic_array_5_fu_515_B_2_ce0),
    .B_2_d0(grp_gemm_systolic_array_5_fu_515_B_2_d0),
    .B_2_q0(v18_2_q0),
    .B_2_we0(grp_gemm_systolic_array_5_fu_515_B_2_we0),
    .B_2_address1(grp_gemm_systolic_array_5_fu_515_B_2_address1),
    .B_2_ce1(grp_gemm_systolic_array_5_fu_515_B_2_ce1),
    .B_2_d1(grp_gemm_systolic_array_5_fu_515_B_2_d1),
    .B_2_q1(32'd0),
    .B_2_we1(grp_gemm_systolic_array_5_fu_515_B_2_we1),
    .B_3_address0(grp_gemm_systolic_array_5_fu_515_B_3_address0),
    .B_3_ce0(grp_gemm_systolic_array_5_fu_515_B_3_ce0),
    .B_3_d0(grp_gemm_systolic_array_5_fu_515_B_3_d0),
    .B_3_q0(v18_3_q0),
    .B_3_we0(grp_gemm_systolic_array_5_fu_515_B_3_we0),
    .B_3_address1(grp_gemm_systolic_array_5_fu_515_B_3_address1),
    .B_3_ce1(grp_gemm_systolic_array_5_fu_515_B_3_ce1),
    .B_3_d1(grp_gemm_systolic_array_5_fu_515_B_3_d1),
    .B_3_q1(32'd0),
    .B_3_we1(grp_gemm_systolic_array_5_fu_515_B_3_we1),
    .C_0_0_address0(grp_gemm_systolic_array_5_fu_515_C_0_0_address0),
    .C_0_0_ce0(grp_gemm_systolic_array_5_fu_515_C_0_0_ce0),
    .C_0_0_d0(grp_gemm_systolic_array_5_fu_515_C_0_0_d0),
    .C_0_0_q0(v19_0_0_q0),
    .C_0_0_we0(grp_gemm_systolic_array_5_fu_515_C_0_0_we0),
    .C_0_0_address1(grp_gemm_systolic_array_5_fu_515_C_0_0_address1),
    .C_0_0_ce1(grp_gemm_systolic_array_5_fu_515_C_0_0_ce1),
    .C_0_0_d1(grp_gemm_systolic_array_5_fu_515_C_0_0_d1),
    .C_0_0_q1(32'd0),
    .C_0_0_we1(grp_gemm_systolic_array_5_fu_515_C_0_0_we1),
    .C_0_1_address0(grp_gemm_systolic_array_5_fu_515_C_0_1_address0),
    .C_0_1_ce0(grp_gemm_systolic_array_5_fu_515_C_0_1_ce0),
    .C_0_1_d0(grp_gemm_systolic_array_5_fu_515_C_0_1_d0),
    .C_0_1_q0(v19_0_1_q0),
    .C_0_1_we0(grp_gemm_systolic_array_5_fu_515_C_0_1_we0),
    .C_0_1_address1(grp_gemm_systolic_array_5_fu_515_C_0_1_address1),
    .C_0_1_ce1(grp_gemm_systolic_array_5_fu_515_C_0_1_ce1),
    .C_0_1_d1(grp_gemm_systolic_array_5_fu_515_C_0_1_d1),
    .C_0_1_q1(32'd0),
    .C_0_1_we1(grp_gemm_systolic_array_5_fu_515_C_0_1_we1),
    .C_0_2_address0(grp_gemm_systolic_array_5_fu_515_C_0_2_address0),
    .C_0_2_ce0(grp_gemm_systolic_array_5_fu_515_C_0_2_ce0),
    .C_0_2_d0(grp_gemm_systolic_array_5_fu_515_C_0_2_d0),
    .C_0_2_q0(v19_0_2_q0),
    .C_0_2_we0(grp_gemm_systolic_array_5_fu_515_C_0_2_we0),
    .C_0_2_address1(grp_gemm_systolic_array_5_fu_515_C_0_2_address1),
    .C_0_2_ce1(grp_gemm_systolic_array_5_fu_515_C_0_2_ce1),
    .C_0_2_d1(grp_gemm_systolic_array_5_fu_515_C_0_2_d1),
    .C_0_2_q1(32'd0),
    .C_0_2_we1(grp_gemm_systolic_array_5_fu_515_C_0_2_we1),
    .C_0_3_address0(grp_gemm_systolic_array_5_fu_515_C_0_3_address0),
    .C_0_3_ce0(grp_gemm_systolic_array_5_fu_515_C_0_3_ce0),
    .C_0_3_d0(grp_gemm_systolic_array_5_fu_515_C_0_3_d0),
    .C_0_3_q0(v19_0_3_q0),
    .C_0_3_we0(grp_gemm_systolic_array_5_fu_515_C_0_3_we0),
    .C_0_3_address1(grp_gemm_systolic_array_5_fu_515_C_0_3_address1),
    .C_0_3_ce1(grp_gemm_systolic_array_5_fu_515_C_0_3_ce1),
    .C_0_3_d1(grp_gemm_systolic_array_5_fu_515_C_0_3_d1),
    .C_0_3_q1(32'd0),
    .C_0_3_we1(grp_gemm_systolic_array_5_fu_515_C_0_3_we1),
    .C_1_0_address0(grp_gemm_systolic_array_5_fu_515_C_1_0_address0),
    .C_1_0_ce0(grp_gemm_systolic_array_5_fu_515_C_1_0_ce0),
    .C_1_0_d0(grp_gemm_systolic_array_5_fu_515_C_1_0_d0),
    .C_1_0_q0(v19_1_0_q0),
    .C_1_0_we0(grp_gemm_systolic_array_5_fu_515_C_1_0_we0),
    .C_1_0_address1(grp_gemm_systolic_array_5_fu_515_C_1_0_address1),
    .C_1_0_ce1(grp_gemm_systolic_array_5_fu_515_C_1_0_ce1),
    .C_1_0_d1(grp_gemm_systolic_array_5_fu_515_C_1_0_d1),
    .C_1_0_q1(32'd0),
    .C_1_0_we1(grp_gemm_systolic_array_5_fu_515_C_1_0_we1),
    .C_1_1_address0(grp_gemm_systolic_array_5_fu_515_C_1_1_address0),
    .C_1_1_ce0(grp_gemm_systolic_array_5_fu_515_C_1_1_ce0),
    .C_1_1_d0(grp_gemm_systolic_array_5_fu_515_C_1_1_d0),
    .C_1_1_q0(v19_1_1_q0),
    .C_1_1_we0(grp_gemm_systolic_array_5_fu_515_C_1_1_we0),
    .C_1_1_address1(grp_gemm_systolic_array_5_fu_515_C_1_1_address1),
    .C_1_1_ce1(grp_gemm_systolic_array_5_fu_515_C_1_1_ce1),
    .C_1_1_d1(grp_gemm_systolic_array_5_fu_515_C_1_1_d1),
    .C_1_1_q1(32'd0),
    .C_1_1_we1(grp_gemm_systolic_array_5_fu_515_C_1_1_we1),
    .C_1_2_address0(grp_gemm_systolic_array_5_fu_515_C_1_2_address0),
    .C_1_2_ce0(grp_gemm_systolic_array_5_fu_515_C_1_2_ce0),
    .C_1_2_d0(grp_gemm_systolic_array_5_fu_515_C_1_2_d0),
    .C_1_2_q0(v19_1_2_q0),
    .C_1_2_we0(grp_gemm_systolic_array_5_fu_515_C_1_2_we0),
    .C_1_2_address1(grp_gemm_systolic_array_5_fu_515_C_1_2_address1),
    .C_1_2_ce1(grp_gemm_systolic_array_5_fu_515_C_1_2_ce1),
    .C_1_2_d1(grp_gemm_systolic_array_5_fu_515_C_1_2_d1),
    .C_1_2_q1(32'd0),
    .C_1_2_we1(grp_gemm_systolic_array_5_fu_515_C_1_2_we1),
    .C_1_3_address0(grp_gemm_systolic_array_5_fu_515_C_1_3_address0),
    .C_1_3_ce0(grp_gemm_systolic_array_5_fu_515_C_1_3_ce0),
    .C_1_3_d0(grp_gemm_systolic_array_5_fu_515_C_1_3_d0),
    .C_1_3_q0(v19_1_3_q0),
    .C_1_3_we0(grp_gemm_systolic_array_5_fu_515_C_1_3_we0),
    .C_1_3_address1(grp_gemm_systolic_array_5_fu_515_C_1_3_address1),
    .C_1_3_ce1(grp_gemm_systolic_array_5_fu_515_C_1_3_ce1),
    .C_1_3_d1(grp_gemm_systolic_array_5_fu_515_C_1_3_d1),
    .C_1_3_q1(32'd0),
    .C_1_3_we1(grp_gemm_systolic_array_5_fu_515_C_1_3_we1),
    .C_2_0_address0(grp_gemm_systolic_array_5_fu_515_C_2_0_address0),
    .C_2_0_ce0(grp_gemm_systolic_array_5_fu_515_C_2_0_ce0),
    .C_2_0_d0(grp_gemm_systolic_array_5_fu_515_C_2_0_d0),
    .C_2_0_q0(v19_2_0_q0),
    .C_2_0_we0(grp_gemm_systolic_array_5_fu_515_C_2_0_we0),
    .C_2_0_address1(grp_gemm_systolic_array_5_fu_515_C_2_0_address1),
    .C_2_0_ce1(grp_gemm_systolic_array_5_fu_515_C_2_0_ce1),
    .C_2_0_d1(grp_gemm_systolic_array_5_fu_515_C_2_0_d1),
    .C_2_0_q1(32'd0),
    .C_2_0_we1(grp_gemm_systolic_array_5_fu_515_C_2_0_we1),
    .C_2_1_address0(grp_gemm_systolic_array_5_fu_515_C_2_1_address0),
    .C_2_1_ce0(grp_gemm_systolic_array_5_fu_515_C_2_1_ce0),
    .C_2_1_d0(grp_gemm_systolic_array_5_fu_515_C_2_1_d0),
    .C_2_1_q0(v19_2_1_q0),
    .C_2_1_we0(grp_gemm_systolic_array_5_fu_515_C_2_1_we0),
    .C_2_1_address1(grp_gemm_systolic_array_5_fu_515_C_2_1_address1),
    .C_2_1_ce1(grp_gemm_systolic_array_5_fu_515_C_2_1_ce1),
    .C_2_1_d1(grp_gemm_systolic_array_5_fu_515_C_2_1_d1),
    .C_2_1_q1(32'd0),
    .C_2_1_we1(grp_gemm_systolic_array_5_fu_515_C_2_1_we1),
    .C_2_2_address0(grp_gemm_systolic_array_5_fu_515_C_2_2_address0),
    .C_2_2_ce0(grp_gemm_systolic_array_5_fu_515_C_2_2_ce0),
    .C_2_2_d0(grp_gemm_systolic_array_5_fu_515_C_2_2_d0),
    .C_2_2_q0(v19_2_2_q0),
    .C_2_2_we0(grp_gemm_systolic_array_5_fu_515_C_2_2_we0),
    .C_2_2_address1(grp_gemm_systolic_array_5_fu_515_C_2_2_address1),
    .C_2_2_ce1(grp_gemm_systolic_array_5_fu_515_C_2_2_ce1),
    .C_2_2_d1(grp_gemm_systolic_array_5_fu_515_C_2_2_d1),
    .C_2_2_q1(32'd0),
    .C_2_2_we1(grp_gemm_systolic_array_5_fu_515_C_2_2_we1),
    .C_2_3_address0(grp_gemm_systolic_array_5_fu_515_C_2_3_address0),
    .C_2_3_ce0(grp_gemm_systolic_array_5_fu_515_C_2_3_ce0),
    .C_2_3_d0(grp_gemm_systolic_array_5_fu_515_C_2_3_d0),
    .C_2_3_q0(v19_2_3_q0),
    .C_2_3_we0(grp_gemm_systolic_array_5_fu_515_C_2_3_we0),
    .C_2_3_address1(grp_gemm_systolic_array_5_fu_515_C_2_3_address1),
    .C_2_3_ce1(grp_gemm_systolic_array_5_fu_515_C_2_3_ce1),
    .C_2_3_d1(grp_gemm_systolic_array_5_fu_515_C_2_3_d1),
    .C_2_3_q1(32'd0),
    .C_2_3_we1(grp_gemm_systolic_array_5_fu_515_C_2_3_we1),
    .C_3_0_address0(grp_gemm_systolic_array_5_fu_515_C_3_0_address0),
    .C_3_0_ce0(grp_gemm_systolic_array_5_fu_515_C_3_0_ce0),
    .C_3_0_d0(grp_gemm_systolic_array_5_fu_515_C_3_0_d0),
    .C_3_0_q0(v19_3_0_q0),
    .C_3_0_we0(grp_gemm_systolic_array_5_fu_515_C_3_0_we0),
    .C_3_0_address1(grp_gemm_systolic_array_5_fu_515_C_3_0_address1),
    .C_3_0_ce1(grp_gemm_systolic_array_5_fu_515_C_3_0_ce1),
    .C_3_0_d1(grp_gemm_systolic_array_5_fu_515_C_3_0_d1),
    .C_3_0_q1(32'd0),
    .C_3_0_we1(grp_gemm_systolic_array_5_fu_515_C_3_0_we1),
    .C_3_1_address0(grp_gemm_systolic_array_5_fu_515_C_3_1_address0),
    .C_3_1_ce0(grp_gemm_systolic_array_5_fu_515_C_3_1_ce0),
    .C_3_1_d0(grp_gemm_systolic_array_5_fu_515_C_3_1_d0),
    .C_3_1_q0(v19_3_1_q0),
    .C_3_1_we0(grp_gemm_systolic_array_5_fu_515_C_3_1_we0),
    .C_3_1_address1(grp_gemm_systolic_array_5_fu_515_C_3_1_address1),
    .C_3_1_ce1(grp_gemm_systolic_array_5_fu_515_C_3_1_ce1),
    .C_3_1_d1(grp_gemm_systolic_array_5_fu_515_C_3_1_d1),
    .C_3_1_q1(32'd0),
    .C_3_1_we1(grp_gemm_systolic_array_5_fu_515_C_3_1_we1),
    .C_3_2_address0(grp_gemm_systolic_array_5_fu_515_C_3_2_address0),
    .C_3_2_ce0(grp_gemm_systolic_array_5_fu_515_C_3_2_ce0),
    .C_3_2_d0(grp_gemm_systolic_array_5_fu_515_C_3_2_d0),
    .C_3_2_q0(v19_3_2_q0),
    .C_3_2_we0(grp_gemm_systolic_array_5_fu_515_C_3_2_we0),
    .C_3_2_address1(grp_gemm_systolic_array_5_fu_515_C_3_2_address1),
    .C_3_2_ce1(grp_gemm_systolic_array_5_fu_515_C_3_2_ce1),
    .C_3_2_d1(grp_gemm_systolic_array_5_fu_515_C_3_2_d1),
    .C_3_2_q1(32'd0),
    .C_3_2_we1(grp_gemm_systolic_array_5_fu_515_C_3_2_we1),
    .C_3_3_address0(grp_gemm_systolic_array_5_fu_515_C_3_3_address0),
    .C_3_3_ce0(grp_gemm_systolic_array_5_fu_515_C_3_3_ce0),
    .C_3_3_d0(grp_gemm_systolic_array_5_fu_515_C_3_3_d0),
    .C_3_3_q0(v19_3_3_q0),
    .C_3_3_we0(grp_gemm_systolic_array_5_fu_515_C_3_3_we0),
    .C_3_3_address1(grp_gemm_systolic_array_5_fu_515_C_3_3_address1),
    .C_3_3_ce1(grp_gemm_systolic_array_5_fu_515_C_3_3_ce1),
    .C_3_3_d1(grp_gemm_systolic_array_5_fu_515_C_3_3_d1),
    .C_3_3_q1(32'd0),
    .C_3_3_we1(grp_gemm_systolic_array_5_fu_515_C_3_3_we1),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_gemm_systolic_array_5_fu_515_ap_start),
    .ap_done(grp_gemm_systolic_array_5_fu_515_ap_done),
    .ap_ready(grp_gemm_systolic_array_5_fu_515_ap_ready),
    .ap_idle(grp_gemm_systolic_array_5_fu_515_ap_idle),
    .ap_continue(grp_gemm_systolic_array_5_fu_515_ap_continue)
);

Bert_layer_fmul_3cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Bert_layer_fmul_3cud_U3637(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v36_fu_821_p18),
    .din1(32'd1040187392),
    .ce(1'b1),
    .dout(grp_fu_567_p2)
);

Bert_layer_mux_16jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
Bert_layer_mux_16jbC_U3638(
    .din0(v19_0_0_q0),
    .din1(v19_0_1_q0),
    .din2(v19_0_2_q0),
    .din3(v19_0_3_q0),
    .din4(v19_1_0_q0),
    .din5(v19_1_1_q0),
    .din6(v19_1_2_q0),
    .din7(v19_1_3_q0),
    .din8(v19_2_0_q0),
    .din9(v19_2_1_q0),
    .din10(v19_2_2_q0),
    .din11(v19_2_3_q0),
    .din12(v19_3_0_q0),
    .din13(v19_3_1_q0),
    .din14(v19_3_2_q0),
    .din15(v19_3_3_q0),
    .din16(v36_fu_821_p17),
    .dout(v36_fu_821_p18)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_gemm_systolic_array_5_fu_515_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_sync_reg_grp_gemm_systolic_array_5_fu_515_ap_done <= 1'b0;
        end else if ((grp_gemm_systolic_array_5_fu_515_ap_done == 1'b1)) begin
            ap_sync_reg_grp_gemm_systolic_array_5_fu_515_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_gemm_systolic_array_5_fu_515_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_sync_reg_grp_gemm_systolic_array_5_fu_515_ap_ready <= 1'b0;
        end else if ((grp_gemm_systolic_array_5_fu_515_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_gemm_systolic_array_5_fu_515_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_gemm_systolic_array_5_fu_515_ap_start_reg <= 1'b0;
    end else begin
        if ((((ap_sync_grp_gemm_systolic_array_5_fu_515_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln40_fu_588_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
            grp_gemm_systolic_array_5_fu_515_ap_start_reg <= 1'b1;
        end else if ((grp_gemm_systolic_array_5_fu_515_ap_ready == 1'b1)) begin
            grp_gemm_systolic_array_5_fu_515_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i2_0_reg_493 <= select_ln51_1_reg_906;
    end else if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        i2_0_reg_493 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        indvar_flatten_reg_482 <= add_ln48_reg_896;
    end else if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        indvar_flatten_reg_482 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        j1_0_reg_504 <= j1_fu_860_p2;
    end else if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        j1_0_reg_504 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_fu_636_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        v20_0_reg_460 <= v20_reg_868;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        v20_0_reg_460 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln40_fu_588_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        v21_0_reg_471 <= 4'd0;
    end else if (((icmp_ln41_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        v21_0_reg_471 <= v21_fu_642_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln48_reg_896 <= add_ln48_fu_697_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln48_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        select_ln51_1_reg_906 <= select_ln51_1_fu_723_p3;
        select_ln51_reg_901 <= select_ln51_fu_715_p3;
        trunc_ln51_1_reg_916 <= trunc_ln51_1_fu_767_p1;
        trunc_ln51_reg_911 <= trunc_ln51_fu_731_p1;
        v19_0_0_addr_1_reg_921 <= sext_ln51_fu_791_p1;
        v19_0_1_addr_1_reg_926 <= sext_ln51_fu_791_p1;
        v19_0_2_addr_1_reg_931 <= sext_ln51_fu_791_p1;
        v19_0_3_addr_1_reg_936 <= sext_ln51_fu_791_p1;
        v19_1_0_addr_1_reg_941 <= sext_ln51_fu_791_p1;
        v19_1_1_addr_1_reg_946 <= sext_ln51_fu_791_p1;
        v19_1_2_addr_1_reg_951 <= sext_ln51_fu_791_p1;
        v19_1_3_addr_1_reg_956 <= sext_ln51_fu_791_p1;
        v19_2_0_addr_1_reg_961 <= sext_ln51_fu_791_p1;
        v19_2_1_addr_1_reg_966 <= sext_ln51_fu_791_p1;
        v19_2_2_addr_1_reg_971 <= sext_ln51_fu_791_p1;
        v19_2_3_addr_1_reg_976 <= sext_ln51_fu_791_p1;
        v19_3_0_addr_1_reg_981 <= sext_ln51_fu_791_p1;
        v19_3_1_addr_1_reg_986 <= sext_ln51_fu_791_p1;
        v19_3_2_addr_1_reg_991 <= sext_ln51_fu_791_p1;
        v19_3_3_addr_1_reg_996 <= sext_ln51_fu_791_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln40_fu_588_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        sub_ln42_reg_877 <= sub_ln42_fu_630_p2;
        trunc_ln42_reg_873 <= trunc_ln42_fu_600_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        v20_reg_868 <= v20_fu_594_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        grp_gemm_systolic_array_5_fu_515_ap_continue = 1'b1;
    end else begin
        grp_gemm_systolic_array_5_fu_515_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_0_0_address0 = v19_0_0_addr_1_reg_921;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_0_0_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_0_0_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_0_address0 = grp_gemm_systolic_array_5_fu_515_C_0_0_address0;
    end else begin
        v19_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_0_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_0_ce0 = grp_gemm_systolic_array_5_fu_515_C_0_0_ce0;
    end else begin
        v19_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_0_0_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_0_0_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_0_d0 = grp_gemm_systolic_array_5_fu_515_C_0_0_d0;
    end else begin
        v19_0_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd0) & (trunc_ln51_reg_911 == 2'd0) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd0) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_0_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_0_we0 = grp_gemm_systolic_array_5_fu_515_C_0_0_we0;
    end else begin
        v19_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_0_1_address0 = v19_0_1_addr_1_reg_926;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_0_1_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_0_1_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_1_address0 = grp_gemm_systolic_array_5_fu_515_C_0_1_address0;
    end else begin
        v19_0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_0_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_1_ce0 = grp_gemm_systolic_array_5_fu_515_C_0_1_ce0;
    end else begin
        v19_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_0_1_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_0_1_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_1_d0 = grp_gemm_systolic_array_5_fu_515_C_0_1_d0;
    end else begin
        v19_0_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd1) & (trunc_ln51_reg_911 == 2'd0) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd1) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_0_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_1_we0 = grp_gemm_systolic_array_5_fu_515_C_0_1_we0;
    end else begin
        v19_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_0_2_address0 = v19_0_2_addr_1_reg_931;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_0_2_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_0_2_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_2_address0 = grp_gemm_systolic_array_5_fu_515_C_0_2_address0;
    end else begin
        v19_0_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_0_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_2_ce0 = grp_gemm_systolic_array_5_fu_515_C_0_2_ce0;
    end else begin
        v19_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_0_2_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_0_2_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_2_d0 = grp_gemm_systolic_array_5_fu_515_C_0_2_d0;
    end else begin
        v19_0_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd2) & (trunc_ln51_reg_911 == 2'd0) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd2) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_0_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_2_we0 = grp_gemm_systolic_array_5_fu_515_C_0_2_we0;
    end else begin
        v19_0_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_0_3_address0 = v19_0_3_addr_1_reg_936;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_0_3_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_0_3_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_3_address0 = grp_gemm_systolic_array_5_fu_515_C_0_3_address0;
    end else begin
        v19_0_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_0_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_3_ce0 = grp_gemm_systolic_array_5_fu_515_C_0_3_ce0;
    end else begin
        v19_0_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_0_3_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_0_3_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_3_d0 = grp_gemm_systolic_array_5_fu_515_C_0_3_d0;
    end else begin
        v19_0_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd3) & (trunc_ln51_reg_911 == 2'd0) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd3) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_0_3_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_0_3_we0 = grp_gemm_systolic_array_5_fu_515_C_0_3_we0;
    end else begin
        v19_0_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_1_0_address0 = v19_1_0_addr_1_reg_941;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_1_0_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_1_0_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_0_address0 = grp_gemm_systolic_array_5_fu_515_C_1_0_address0;
    end else begin
        v19_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_1_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_0_ce0 = grp_gemm_systolic_array_5_fu_515_C_1_0_ce0;
    end else begin
        v19_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_1_0_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_1_0_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_0_d0 = grp_gemm_systolic_array_5_fu_515_C_1_0_d0;
    end else begin
        v19_1_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd0) & (trunc_ln51_reg_911 == 2'd1) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd0) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_1_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_0_we0 = grp_gemm_systolic_array_5_fu_515_C_1_0_we0;
    end else begin
        v19_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_1_1_address0 = v19_1_1_addr_1_reg_946;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_1_1_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_1_1_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_1_address0 = grp_gemm_systolic_array_5_fu_515_C_1_1_address0;
    end else begin
        v19_1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_1_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_1_ce0 = grp_gemm_systolic_array_5_fu_515_C_1_1_ce0;
    end else begin
        v19_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_1_1_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_1_1_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_1_d0 = grp_gemm_systolic_array_5_fu_515_C_1_1_d0;
    end else begin
        v19_1_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd1) & (trunc_ln51_reg_911 == 2'd1) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd1) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_1_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_1_we0 = grp_gemm_systolic_array_5_fu_515_C_1_1_we0;
    end else begin
        v19_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_1_2_address0 = v19_1_2_addr_1_reg_951;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_1_2_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_1_2_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_2_address0 = grp_gemm_systolic_array_5_fu_515_C_1_2_address0;
    end else begin
        v19_1_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_1_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_2_ce0 = grp_gemm_systolic_array_5_fu_515_C_1_2_ce0;
    end else begin
        v19_1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_1_2_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_1_2_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_2_d0 = grp_gemm_systolic_array_5_fu_515_C_1_2_d0;
    end else begin
        v19_1_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd2) & (trunc_ln51_reg_911 == 2'd1) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd2) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_1_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_2_we0 = grp_gemm_systolic_array_5_fu_515_C_1_2_we0;
    end else begin
        v19_1_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_1_3_address0 = v19_1_3_addr_1_reg_956;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_1_3_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_1_3_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_3_address0 = grp_gemm_systolic_array_5_fu_515_C_1_3_address0;
    end else begin
        v19_1_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_1_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_3_ce0 = grp_gemm_systolic_array_5_fu_515_C_1_3_ce0;
    end else begin
        v19_1_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_1_3_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_1_3_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_3_d0 = grp_gemm_systolic_array_5_fu_515_C_1_3_d0;
    end else begin
        v19_1_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd3) & (trunc_ln51_reg_911 == 2'd1) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd3) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_1_3_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_1_3_we0 = grp_gemm_systolic_array_5_fu_515_C_1_3_we0;
    end else begin
        v19_1_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_2_0_address0 = v19_2_0_addr_1_reg_961;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_2_0_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_2_0_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_0_address0 = grp_gemm_systolic_array_5_fu_515_C_2_0_address0;
    end else begin
        v19_2_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_2_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_0_ce0 = grp_gemm_systolic_array_5_fu_515_C_2_0_ce0;
    end else begin
        v19_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_2_0_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_2_0_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_0_d0 = grp_gemm_systolic_array_5_fu_515_C_2_0_d0;
    end else begin
        v19_2_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd0) & (trunc_ln51_reg_911 == 2'd2) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd0) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_2_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_0_we0 = grp_gemm_systolic_array_5_fu_515_C_2_0_we0;
    end else begin
        v19_2_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_2_1_address0 = v19_2_1_addr_1_reg_966;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_2_1_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_2_1_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_1_address0 = grp_gemm_systolic_array_5_fu_515_C_2_1_address0;
    end else begin
        v19_2_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_2_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_1_ce0 = grp_gemm_systolic_array_5_fu_515_C_2_1_ce0;
    end else begin
        v19_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_2_1_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_2_1_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_1_d0 = grp_gemm_systolic_array_5_fu_515_C_2_1_d0;
    end else begin
        v19_2_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd1) & (trunc_ln51_reg_911 == 2'd2) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd1) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_2_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_1_we0 = grp_gemm_systolic_array_5_fu_515_C_2_1_we0;
    end else begin
        v19_2_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_2_2_address0 = v19_2_2_addr_1_reg_971;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_2_2_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_2_2_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_2_address0 = grp_gemm_systolic_array_5_fu_515_C_2_2_address0;
    end else begin
        v19_2_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_2_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_2_ce0 = grp_gemm_systolic_array_5_fu_515_C_2_2_ce0;
    end else begin
        v19_2_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_2_2_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_2_2_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_2_d0 = grp_gemm_systolic_array_5_fu_515_C_2_2_d0;
    end else begin
        v19_2_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd2) & (trunc_ln51_reg_911 == 2'd2) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd2) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_2_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_2_we0 = grp_gemm_systolic_array_5_fu_515_C_2_2_we0;
    end else begin
        v19_2_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_2_3_address0 = v19_2_3_addr_1_reg_976;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_2_3_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_2_3_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_3_address0 = grp_gemm_systolic_array_5_fu_515_C_2_3_address0;
    end else begin
        v19_2_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_2_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_3_ce0 = grp_gemm_systolic_array_5_fu_515_C_2_3_ce0;
    end else begin
        v19_2_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_2_3_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_2_3_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_3_d0 = grp_gemm_systolic_array_5_fu_515_C_2_3_d0;
    end else begin
        v19_2_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd3) & (trunc_ln51_reg_911 == 2'd2) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd3) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_2_3_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_2_3_we0 = grp_gemm_systolic_array_5_fu_515_C_2_3_we0;
    end else begin
        v19_2_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_3_0_address0 = v19_3_0_addr_1_reg_981;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_3_0_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_3_0_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_0_address0 = grp_gemm_systolic_array_5_fu_515_C_3_0_address0;
    end else begin
        v19_3_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_3_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_0_ce0 = grp_gemm_systolic_array_5_fu_515_C_3_0_ce0;
    end else begin
        v19_3_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_3_0_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_3_0_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_0_d0 = grp_gemm_systolic_array_5_fu_515_C_3_0_d0;
    end else begin
        v19_3_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd0) & (trunc_ln51_reg_911 == 2'd3) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd0) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd3) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_3_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_0_we0 = grp_gemm_systolic_array_5_fu_515_C_3_0_we0;
    end else begin
        v19_3_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_3_1_address0 = v19_3_1_addr_1_reg_986;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_3_1_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_3_1_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_1_address0 = grp_gemm_systolic_array_5_fu_515_C_3_1_address0;
    end else begin
        v19_3_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_3_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_1_ce0 = grp_gemm_systolic_array_5_fu_515_C_3_1_ce0;
    end else begin
        v19_3_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_3_1_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_3_1_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_1_d0 = grp_gemm_systolic_array_5_fu_515_C_3_1_d0;
    end else begin
        v19_3_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd1) & (trunc_ln51_reg_911 == 2'd3) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd1) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd3) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_3_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_1_we0 = grp_gemm_systolic_array_5_fu_515_C_3_1_we0;
    end else begin
        v19_3_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_3_2_address0 = v19_3_2_addr_1_reg_991;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_3_2_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_3_2_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_2_address0 = grp_gemm_systolic_array_5_fu_515_C_3_2_address0;
    end else begin
        v19_3_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_3_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_2_ce0 = grp_gemm_systolic_array_5_fu_515_C_3_2_ce0;
    end else begin
        v19_3_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_3_2_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_3_2_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_2_d0 = grp_gemm_systolic_array_5_fu_515_C_3_2_d0;
    end else begin
        v19_3_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd2) & (trunc_ln51_reg_911 == 2'd3) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd2) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd3) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_3_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_2_we0 = grp_gemm_systolic_array_5_fu_515_C_3_2_we0;
    end else begin
        v19_3_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_3_3_address0 = v19_3_3_addr_1_reg_996;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v19_3_3_address0 = sext_ln51_fu_791_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_3_3_address0 = sext_ln42_fu_671_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_3_address0 = grp_gemm_systolic_array_5_fu_515_C_3_3_address0;
    end else begin
        v19_3_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        v19_3_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_3_ce0 = grp_gemm_systolic_array_5_fu_515_C_3_3_ce0;
    end else begin
        v19_3_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        v19_3_3_d0 = grp_fu_567_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v19_3_3_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_3_d0 = grp_gemm_systolic_array_5_fu_515_C_3_3_d0;
    end else begin
        v19_3_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln51_1_reg_916 == 2'd3) & (trunc_ln51_reg_911 == 2'd3) & (1'b1 == ap_CS_fsm_state9)) | ((trunc_ln42_1_fu_648_p1 == 2'd3) & (icmp_ln41_fu_636_p2 == 1'd0) & (trunc_ln42_reg_873 == 2'd3) & (1'b1 == ap_CS_fsm_state3)))) begin
        v19_3_3_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v19_3_3_we0 = grp_gemm_systolic_array_5_fu_515_C_3_3_we0;
    end else begin
        v19_3_3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln40_fu_588_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln41_fu_636_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln48_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln42_fu_666_p2 = (sub_ln42_reg_877 + zext_ln42_2_fu_662_p1);

assign add_ln48_fu_697_p2 = (indvar_flatten_reg_482 + 8'd1);

assign add_ln51_fu_785_p2 = (zext_ln51_2_fu_781_p1 + sub_ln51_fu_761_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((ap_sync_grp_gemm_systolic_array_5_fu_515_ap_ready & ap_sync_grp_gemm_systolic_array_5_fu_515_ap_done) == 1'b0);
end

assign ap_sync_grp_gemm_systolic_array_5_fu_515_ap_done = (grp_gemm_systolic_array_5_fu_515_ap_done | ap_sync_reg_grp_gemm_systolic_array_5_fu_515_ap_done);

assign ap_sync_grp_gemm_systolic_array_5_fu_515_ap_ready = (grp_gemm_systolic_array_5_fu_515_ap_ready | ap_sync_reg_grp_gemm_systolic_array_5_fu_515_ap_ready);

assign grp_gemm_systolic_array_5_fu_515_ap_start = grp_gemm_systolic_array_5_fu_515_ap_start_reg;

assign i2_fu_703_p2 = (4'd1 + i2_0_reg_493);

assign icmp_ln40_fu_588_p2 = ((v20_0_reg_460 == 4'd12) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_636_p2 = ((v21_0_reg_471 == 4'd12) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_691_p2 = ((indvar_flatten_reg_482 == 8'd144) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_709_p2 = ((j1_0_reg_504 == 4'd12) ? 1'b1 : 1'b0);

assign j1_fu_860_p2 = (select_ln51_reg_901 + 4'd1);

assign lshr_ln_fu_604_p4 = {{v20_0_reg_460[3:2]}};

assign select_ln51_1_fu_723_p3 = ((icmp_ln49_fu_709_p2[0:0] === 1'b1) ? i2_fu_703_p2 : i2_0_reg_493);

assign select_ln51_fu_715_p3 = ((icmp_ln49_fu_709_p2[0:0] === 1'b1) ? 4'd0 : j1_0_reg_504);

assign sext_ln42_fu_671_p1 = $signed(add_ln42_fu_666_p2);

assign sext_ln51_fu_791_p1 = $signed(add_ln51_fu_785_p2);

assign sub_ln42_fu_630_p2 = (zext_ln42_1_fu_626_p1 - zext_ln42_fu_614_p1);

assign sub_ln51_fu_761_p2 = (zext_ln51_1_fu_757_p1 - zext_ln51_fu_745_p1);

assign tmp_231_fu_811_p3 = {{trunc_ln51_reg_911}, {trunc_ln51_1_reg_916}};

assign tmp_233_fu_749_p3 = {{zext_ln51_mid2_v_fu_735_p4}, {2'd0}};

assign tmp_507_fu_771_p4 = {{select_ln51_fu_715_p3[3:2]}};

assign tmp_508_fu_652_p4 = {{v21_0_reg_471[3:2]}};

assign tmp_fu_618_p3 = {{lshr_ln_fu_604_p4}, {2'd0}};

assign trunc_ln42_1_fu_648_p1 = v21_0_reg_471[1:0];

assign trunc_ln42_fu_600_p1 = v20_0_reg_460[1:0];

assign trunc_ln51_1_fu_767_p1 = select_ln51_fu_715_p3[1:0];

assign trunc_ln51_fu_731_p1 = select_ln51_1_fu_723_p3[1:0];

assign v17_0_address0 = grp_gemm_systolic_array_5_fu_515_A_0_address0;

assign v17_0_ce0 = grp_gemm_systolic_array_5_fu_515_A_0_ce0;

assign v17_1_address0 = grp_gemm_systolic_array_5_fu_515_A_1_address0;

assign v17_1_ce0 = grp_gemm_systolic_array_5_fu_515_A_1_ce0;

assign v17_2_address0 = grp_gemm_systolic_array_5_fu_515_A_2_address0;

assign v17_2_ce0 = grp_gemm_systolic_array_5_fu_515_A_2_ce0;

assign v17_3_address0 = grp_gemm_systolic_array_5_fu_515_A_3_address0;

assign v17_3_ce0 = grp_gemm_systolic_array_5_fu_515_A_3_ce0;

assign v18_0_address0 = grp_gemm_systolic_array_5_fu_515_B_0_address0;

assign v18_0_ce0 = grp_gemm_systolic_array_5_fu_515_B_0_ce0;

assign v18_1_address0 = grp_gemm_systolic_array_5_fu_515_B_1_address0;

assign v18_1_ce0 = grp_gemm_systolic_array_5_fu_515_B_1_ce0;

assign v18_2_address0 = grp_gemm_systolic_array_5_fu_515_B_2_address0;

assign v18_2_ce0 = grp_gemm_systolic_array_5_fu_515_B_2_ce0;

assign v18_3_address0 = grp_gemm_systolic_array_5_fu_515_B_3_address0;

assign v18_3_ce0 = grp_gemm_systolic_array_5_fu_515_B_3_ce0;

assign v20_fu_594_p2 = (v20_0_reg_460 + 4'd1);

assign v21_fu_642_p2 = (v21_0_reg_471 + 4'd1);

assign v36_fu_821_p17 = tmp_231_fu_811_p3;

assign zext_ln42_1_fu_626_p1 = tmp_fu_618_p3;

assign zext_ln42_2_fu_662_p1 = tmp_508_fu_652_p4;

assign zext_ln42_fu_614_p1 = lshr_ln_fu_604_p4;

assign zext_ln51_1_fu_757_p1 = tmp_233_fu_749_p3;

assign zext_ln51_2_fu_781_p1 = tmp_507_fu_771_p4;

assign zext_ln51_fu_745_p1 = zext_ln51_mid2_v_fu_735_p4;

assign zext_ln51_mid2_v_fu_735_p4 = {{select_ln51_1_fu_723_p3[3:2]}};

endmodule //Attention_layer
