#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("v242", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("v243", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("v244", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("v245", 32, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("v246", 32, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("v247", 32, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("v248", 32, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("v249", 32, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("v250", 32, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("v251", 32, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("v252", 32, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("v253", 32, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("v254", 32, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("v255", 32, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("v256", 32, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("v257", 32, hls_in, 15, "ap_none", "in_data", 1),
	Port_Property("v258", 32, hls_in, 16, "ap_none", "in_data", 1),
	Port_Property("v259", 32, hls_out, 17, "ap_vld", "out_data", 1),
	Port_Property("v259_ap_vld", 1, hls_out, 17, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "Bert_layer";
